import 'dart:convert';
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:news/model/news_model.dart';
import 'package:http/http.dart' as http;

class MainPage extends StatefulWidget {
  const MainPage({Key? key}) : super(key: key);

  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  var news_url =
      'https://newsapi.org/v2/everything?q=tesla&from=2023-03-13&sortBy=publishedAt&apiKey=0233f77edeb244d2aba812fad1f61d3f';
  late Future<Autogenerated> futurenews;

  @override
  void initState() {
    futurenews = getnews();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('News'),
        centerTitle: true,
        backgroundColor: Colors.grey,
      ),
      body: FutureBuilder(
        future: futurenews,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return ListView.builder(
              itemCount: snapshot.data!.articles!.length,
              itemBuilder: (context, index) {
                return ListTile(
                  leading: CircleAvatar(
                    backgroundImage: NetworkImage(
                        '${snapshot.data!.articles![index].urlToImage}'),
                  ),
                  title: Column(
                    children: [
                      Text('${snapshot.data!.articles![index].author}'),
                      SizedBox(
                        height: 5,
                      ),
                      Text('${snapshot.data!.articles![index].title}'),
                      SizedBox(
                        height: 5,
                      ),
                    ],
                  ),
                  subtitle: Column(
                    children: [
                      Text('${snapshot.data!.articles![index].description}'),
                      SizedBox(
                        height: 5,
                      ),
                      Text('${snapshot.data!.articles![index].url}'),
                      SizedBox(
                        height: 5,
                      ),
                      Text('${snapshot.data!.articles![index].publishedAt}'),
                      SizedBox(
                        height: 5,
                      ),
                      Text('${snapshot.data!.articles![index].content}'),
                    ],
                  ),
                );
              },
            );
          } else if (snapshot.hasError) {
            return Center(
              child: Text('${snapshot.hasError}'),
            );
          } else {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
        },
      ),
    );
  }

  Future<Autogenerated> getnews() async {
    var response = await http.get(Uri.parse(news_url));
    if (response.statusCode == 200) {
      log('${response.statusCode}');
      var news = jsonDecode(response.body);
      return Autogenerated.fromJson(news);
    } else {
      log('Data not found ${response.statusCode}');
      return Autogenerated();
    }
  }
}
